config/routes.rb
Rails.application.routes.draw do
  # www redirect
  match '(*any)', to: redirect(subdomain: ''), via: :all, constraints: {subdomain: 'www'}

  get 'lifetime', to: 'lifetime#index'
  resources :players, only: [:show]
  resources :teams, only: [:show]

  root to: "overview#index"
end

app/views/rankings/_double.html.erb
<h1 id="double" class="subtitle">Beste Doppelspieler</h1>
<label class="expandable-table expandable-table--active">
  <input type="checkbox"/>
  <span>anzeigen</span>
  <table class="table is-striped is-fullwidth">
    <thead>
      <tr>
        <th><abbr title="Platz">Pl</abbr></th>
        <th>Name</th>
        <th><abbr title="Leistungsindex">LI</abbr></th>
        <th><abbr title="Spiele">S</abbr></th>
        <th><abbr title="Spiele gewonnen">SP+</abbr></th>
        <th><abbr title="Spiele verloren">SP-</abbr></th>
        <th><abbr title="Quote">Q</abbr></th>
        <th><abbr title="Tore">T</abbr></th>
        <th><abbr title="Gegentoren">GT</abbr></th>
        <th><abbr title="Tordifferenz">TD</abbr></th>
      </tr>
    </thead>
    <tbody>
      <% local_assigns[:stat].each_with_index do |stat, index| %>
        <tr>
          <td><%= index + 1%></td>
          <td><%= link_to(stat.player.name, player_path(stat.player)) %></td>
          <td><%= stat.double_performance_index %></td>
          <td><%= stat.double_total_score %></td>
          <td><%= stat.double_score %></td>
          <td><%= stat.double_score_against %></td>
          <td><%= stat.double_percentage %>%</td>
          <td><%= stat.double_goals %></td>
          <td><%= stat.double_goals_against %></td>
          <td><%= stat.double_goal_difference %></td>
      <% end %>
    </tbody>
  </table>
</label>

app/views/rankings/_overall.html.erb
<h1 id="overall" class="subtitle">Beste Gesamtspieler</h1>
<label class="expandable-table expandable-table--active">
  <input type="checkbox"/>
  <span>anzeigen</span>
  <table class="table is-striped is-fullwidth">
    <thead>
      <tr>
        <th><abbr title="Platz">Pl</abbr></th>
        <th>Name</th>
        <th><abbr title="Leistungsindex">LI</abbr></th>
        <th><abbr title="Spiele">S</abbr></th>
        <th><abbr title="Spiele gewonnen">SP+</abbr></th>
        <th><abbr title="Spiele verloren">SP-</abbr></th>
        <th><abbr title="Quote">Q</abbr></th>
        <th><abbr title="Tore">T</abbr></th>
        <th><abbr title="Gegentoren">GT</abbr></th>
        <th><abbr title="Tordifferenz">TD</abbr></th>
      </tr>
    </thead>
    <tbody>
      <% local_assigns[:stat].each_with_index do |stat, index| %>
        <tr>
          <td><%= index + 1%></td>
          <td><%= link_to(stat.player.name, player_path(stat.player)) %></td>
          <td><%= stat.overall_performance_index %></td>
          <td><%= stat.overall_total_score %></td>
          <td><%= stat.overall_score %></td>
          <td><%= stat.overall_score_against %></td>
          <td><%= stat.overall_percentage %>%</td>
          <td><%= stat.overall_goals %></td>
          <td><%= stat.overall_goals_against %></td>
          <td><%= stat.overall_goal_difference %></td>
      <% end %>
    </tbody>
  </table>
</label>

app/views/rankings/_pair.html.erb
<h1 id="pair" class="subtitle">Beste Doppelpaare</h1>
<label class="expandable-table expandable-table--active">
  <input type="checkbox"/>
  <span>anzeigen</span>
  <table class="table is-striped is-fullwidth">
    <thead>
      <tr>
        <th><abbr title="Platz">Pl</abbr></th>
        <th>Name</th>
        <th><abbr title="Leistungsindex">LI</abbr></th>
        <th><abbr title="Spiele">S</abbr></th>
        <th><abbr title="Spiele gewonnen">SP+</abbr></th>
        <th><abbr title="Spiele verloren">SP-</abbr></th>
        <th><abbr title="Quote">Q</abbr></th>
        <th><abbr title="Tore">T</abbr></th>
        <th><abbr title="Gegentoren">GT</abbr></th>
        <th><abbr title="Tordifferenz">TD</abbr></th>
      </tr>
    </thead>
    <tbody>
      <% local_assigns[:stat].each_with_index do |stat, index| %>
        <tr>
          <td><%= index + 1%></td>
          <td><%= linked_player_names(stat.players) %> </td>
          <td><%= stat.overall_performance_index %></td>
          <td><%= stat.total_score %></td>
          <td><%= stat.overall_score %></td>
          <td><%= stat.overall_score_against %></td>
          <td><%= stat.percentage %>%</td>
          <td><%= stat.overall_goals %></td>
          <td><%= stat.overall_goals_against %></td>
          <td><%= stat.goal_difference %></td>
      <% end %>
    </tbody>
  </table>
</label>

app/views/rankings/_single.html.erb
<h1 id="single" class="subtitle">Beste Einzelspieler</h1>
<label class="expandable-table expandable-table--active">
  <input type="checkbox"/>
  <span>anzeigen</span>
  <table class="table is-striped is-fullwidth">
    <thead>
      <tr>
        <th><abbr title="Platz">Pl</abbr></th>
        <th>Name</th>
        <th><abbr title="Leistungsindex">LI</abbr></th>
        <th><abbr title="Spiele">S</abbr></th>
        <th><abbr title="Spiele gewonnen">SP+</abbr></th>
        <th><abbr title="Spiele verloren">SP-</abbr></th>
        <th><abbr title="Quote">Q</abbr></th>
        <th><abbr title="Tore">T</abbr></th>
        <th><abbr title="Gegentoren">GT</abbr></th>
        <th><abbr title="Tordifferenz">TD</abbr></th>
      </tr>
    </thead>
    <tbody>
      <% local_assigns[:stat].each_with_index do |stat, index| %>
        <tr>
          <td><%= index + 1%></td>
          <td><%= link_to(stat.player.name, player_path(stat.player)) %></td>
          <td><%= stat.single_performance_index %></td>
          <td><%= stat.single_total_score %></td>
          <td><%= stat.single_score %></td>
          <td><%= stat.single_score_against %></td>
          <td><%= stat.single_percentage %>%</td>
          <td><%= stat.single_goals %></td>
          <td><%= stat.single_goals_against %></td>
          <td><%= stat.single_goal_difference %></td>
      <% end %>
    </tbody>
  </table>
</label>

app/views/rankings/_team.html.erb
<h1 id="team" class="subtitle">Tabelle</h1>
<table class="table is-striped is-fullwidth">
  <thead>
    <tr>
      <th><abbr title="Platz">Pl</abbr></th>
      <th>Team</th>
      <th><abbr title="Begegnungen">B</abbr></th>
      <th><abbr title="Siege">S</abbr></th>
      <th><abbr title="Unentschieden">U</abbr></th>
      <th><abbr title="Verloren">N</abbr></th>
      <th><abbr title="Tore">T</abbr></th>
      <th><abbr title="Gegentoren">GT</abbr></th>
      <th><abbr title="Tordifferenz">TD</abbr></th>
      <th><abbr title="Spiele gewonnen">SG</abbr></th>
      <th><abbr title="Spiele verlore">SV</abbr></th>
      <th><abbr title="Spieldifferenz">SD</abbr></th>
      <th><abbr title="Punkte">Pkt</abbr></th>
    </tr>
  </thead>
  <tbody>
    <% local_assigns[:teams].each_with_index do |team, index| %>
      <tr>
        <td><%= index + 1%></td>
        <td><%= team.name %></td>
        <td><%= team.matches.count %></td>
        <td><%= team.matches_won %></td>
        <td><%= team.matches_draw %></td>
        <td><%= team.matches_lost %></td>
        <td><%= team.goals %></td>
        <td><%= team.goals_against %></td>
        <td><%= team.goal_difference %></td>
        <td><%= team.score %></td>
        <td><%= team.score_against %></td>
        <td><%= team.score_difference %></td>
        <td><%= team.points %></td>
    <% end %>
  </tbody>
</table>